name: Open new issue
on: push

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue title 01" --body "Issue body 01"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


